<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstLocationVisable</name>
   <tag></tag>
   <elementGuidId>2b6cf165-e4f6-400a-9dc0-d8710503f483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[1]/div/span/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[1]/div/span/div/span/span</value>
   </webElementProperties>
</WebElementEntity>
