<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hoverHeading</name>
   <tag></tag>
   <elementGuidId>0f94db2f-ec13-475d-97f5-1048439c48b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;{{settings.treeId}}_tv_active&quot;]//span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;{{settings.treeId}}_tv_active&quot;]//span/span</value>
   </webElementProperties>
</WebElementEntity>
