<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linkClickable</name>
   <tag></tag>
   <elementGuidId>0cfde00e-62e1-43ad-9021-4f9a389b9082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tabstrip&quot;]/ul/li[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tabstrip&quot;]/ul/li[2]/span[2]</value>
   </webElementProperties>
</WebElementEntity>
