<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>locations</name>
   <tag></tag>
   <elementGuidId>a6e83a9a-d17d-43f1-9aa2-697cbde2175b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-manage-resource-list-view-data&quot;]//div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-manage-resource-list-view-data&quot;]//div[4]</value>
   </webElementProperties>
</WebElementEntity>
