<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>setNewLocationName</name>
   <tag></tag>
   <elementGuidId>30b06f8d-8ee5-4c6d-82d6-b50d6ffdcdbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;{{settings.treeId}}_tv_active&quot;]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;{{settings.treeId}}_tv_active&quot;]//input</value>
   </webElementProperties>
</WebElementEntity>
