<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>testAttLoad</name>
   <tag></tag>
   <elementGuidId>0ba37794-9cdd-496b-91b0-282f5315aa63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;master-data-sortable&quot;]/li[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;master-data-sortable&quot;]/li[1]/div</value>
   </webElementProperties>
</WebElementEntity>
