<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yesDelete</name>
   <tag></tag>
   <elementGuidId>9dca731e-7033-489b-9813-01cf1c99b5ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[2]</value>
   </webElementProperties>
</WebElementEntity>
