<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>editForm</name>
   <tag></tag>
   <elementGuidId>03e0e674-15fa-4bdd-8e53-922467cd3ae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-record-viewer-right-panel&quot;]/div/div[1]//span[3]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-record-viewer-right-panel&quot;]/div/div[1]//span[3]</value>
   </webElementProperties>
</WebElementEntity>
