<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>assign_Task</name>
   <tag></tag>
   <elementGuidId>b30edeea-c2eb-4c8b-b706-800678a25e73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-documentmgmt-header-section&quot;]/div/span[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-documentmgmt-header-section&quot;]/div/span[5]</value>
   </webElementProperties>
</WebElementEntity>
