<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>commentBox</name>
   <tag></tag>
   <elementGuidId>66c8b8f1-1640-4cf2-9a63-077853a45c73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-upload-new-doc-dms-body-popup&quot;]/div/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-upload-new-doc-dms-body-popup&quot;]/div/div/div/textarea</value>
   </webElementProperties>
</WebElementEntity>
