<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deleteDocumentDMS</name>
   <tag></tag>
   <elementGuidId>3215c620-b2ff-4c22-867f-390d7009117a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-product-dropdown_listbox&quot;]/li[last()]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-product-dropdown_listbox&quot;]/li[last()]</value>
   </webElementProperties>
</WebElementEntity>
