<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>descriptionField</name>
   <tag></tag>
   <elementGuidId>1a30cd98-27b3-4913-9b87-14b907ba88d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-edit-doc-dms-body-popup&quot;]/div/div/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-edit-doc-dms-body-popup&quot;]/div/div/div/div/textarea</value>
   </webElementProperties>
</WebElementEntity>
