<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>download</name>
   <tag></tag>
   <elementGuidId>e518418f-e69a-4f91-936d-46a5eae483d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-documentmgmt-header-section&quot;]/div[2]/span[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-documentmgmt-header-section&quot;]/div[2]/span[6]</value>
   </webElementProperties>
</WebElementEntity>
