<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newDocumentField</name>
   <tag></tag>
   <elementGuidId>42c9e841-20f7-40e4-8eda-dd5db9adec5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-left-panel-treeview&quot;]/ul/li[last()]/div/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-left-panel-treeview&quot;]/ul/li[last()]/div/span/span/span</value>
   </webElementProperties>
</WebElementEntity>
