<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>restoreButton</name>
   <tag></tag>
   <elementGuidId>b1bf1485-7b5c-40ba-92c6-331c24d1f52d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-documentmgmt-header-section&quot;]/div/span[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-documentmgmt-header-section&quot;]/div/span[8]</value>
   </webElementProperties>
</WebElementEntity>
