<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectInDocument1</name>
   <tag></tag>
   <elementGuidId>7c8ead96-b61d-4ae2-bada-83c10feb1ec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-documents-grid&quot;]/div/table/tbody/tr/td[contains(text(),&quot;Lighthouse.jpg&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-documents-grid&quot;]/div/table/tbody/tr/td[contains(text(),&quot;Lighthouse.jpg&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
