<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectLinkToResource</name>
   <tag></tag>
   <elementGuidId>45a11732-de17-4407-a08f-cd8414728174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;grid-Customers&quot;]/div[2]/div[1]/table/tbody/tr[1]/td[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;grid-Customers&quot;]/div[2]/div[1]/table/tbody/tr[1]/td[1]/input</value>
   </webElementProperties>
</WebElementEntity>
