<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectInDocument3</name>
   <tag></tag>
   <elementGuidId>80fc1de2-2634-4db7-b1d1-3e839f1f3455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-documents-grid&quot;]/div/table/tbody/tr/td[contains(text(),&quot;Penguins.jpg&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-documents-grid&quot;]/div/table/tbody/tr/td[contains(text(),&quot;Penguins.jpg&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
