<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectTask</name>
   <tag></tag>
   <elementGuidId>25e64282-8a11-4e21-8a54-858d2fdda0e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-inbox-grid-container&quot;]/div/table/tbody/tr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-inbox-grid-container&quot;]/div/table/tbody/tr</value>
   </webElementProperties>
</WebElementEntity>
