<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>viewdeletedDocument</name>
   <tag></tag>
   <elementGuidId>457f3dbe-9e7d-4662-9b7b-c963404d3d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-left-panel-treeview&quot;]/ul/li/div/span/span/span[contains(text(),&quot;new&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-left-panel-treeview&quot;]/ul/li/div/span/span/span[contains(text(),&quot;new&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
