<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add1singleValue1</name>
   <tag></tag>
   <elementGuidId>e38aa697-0d2b-4005-a355-6a7787491f5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-designform-form-content-prop-area&quot;]/div/div/div/div/div/div/div/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-designform-form-content-prop-area&quot;]/div/div/div/div/div/div/div/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
