<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addSingleValue1</name>
   <tag></tag>
   <elementGuidId>63741ac7-0479-4d1f-b301-40c621d342e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-designform-form-content-prop-area&quot;]/div[2]/div/div[3]/div/div/div/div[3]/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-designform-form-content-prop-area&quot;]/div[2]/div/div[3]/div/div/div/div[3]/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
