<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>copySection</name>
   <tag></tag>
   <elementGuidId>e4843f1b-b698-42ef-a445-6f139ec75d65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;field-Section-0&quot;]/div[1]/div/div[2]/i[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;field-Section-0&quot;]/div[1]/div/div[2]/i[5]</value>
   </webElementProperties>
</WebElementEntity>
