<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>formDesign_SingleLineName</name>
   <tag></tag>
   <elementGuidId>d62f4948-1328-4c8d-aec6-bb96f722c441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;field-SingleLineText-0&quot;]/div[1]/div[1]/div[2]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;field-SingleLineText-0&quot;]/div[1]/div[1]/div[2]/span/input</value>
   </webElementProperties>
</WebElementEntity>
