<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>formDesign_Select_SelectOne</name>
   <tag></tag>
   <elementGuidId>dd801c56-e51f-443f-a2d6-8626fddbcf92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-designform-left-panel-fields-contents&quot;]/li[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-designform-left-panel-fields-contents&quot;]/li[3]/div/span</value>
   </webElementProperties>
</WebElementEntity>
