<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>formDesign_DateName_Text</name>
   <tag></tag>
   <elementGuidId>1cc4c46d-a7f0-483c-8f4c-cb2cd0623b72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;field-Date-0&quot;]/div[1]/div[1]/div[2]/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;field-Date-0&quot;]/div[1]/div[1]/div[2]/span/textarea</value>
   </webElementProperties>
</WebElementEntity>
