<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>formDesign_SelectNumeric</name>
   <tag></tag>
   <elementGuidId>82182ff9-b745-47ff-a649-7ec7131fe9ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-designform-left-panel-fields-contents&quot;]/li[5]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-designform-left-panel-fields-contents&quot;]/li[5]/div/span</value>
   </webElementProperties>
</WebElementEntity>
