<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>formDesign_DateTimeName_Text</name>
   <tag></tag>
   <elementGuidId>ff630822-ce54-49a4-85cc-49ccb76575f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;field-DateTime-0&quot;]/div[1]/div[1]/div[2]/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;field-DateTime-0&quot;]/div[1]/div[1]/div[2]/span/textarea</value>
   </webElementProperties>
</WebElementEntity>
