<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>openResType</name>
   <tag></tag>
   <elementGuidId>ad103645-9605-4787-a621-d35862360d88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='scs-form-designer-selectresource-container']/div/div/div[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='scs-form-designer-selectresource-container']/div/div/div[1]/span</value>
   </webElementProperties>
</WebElementEntity>
