<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectEquipment</name>
   <tag></tag>
   <elementGuidId>83ad2f7c-f0b9-48b8-a2f4-a7c146962702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='scs-product-dropdown_listbox']/li[contains(text(),'Equipment')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='scs-product-dropdown_listbox']/li[contains(text(),'Equipment')]</value>
   </webElementProperties>
</WebElementEntity>
