<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select1Res</name>
   <tag></tag>
   <elementGuidId>dc0d0649-eff3-45eb-88ed-4f2b3d2f2522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[2]/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[2]/div/span[2]</value>
   </webElementProperties>
</WebElementEntity>
