<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectQuestionaireForm</name>
   <tag></tag>
   <elementGuidId>4c37b322-ca0e-4a5e-a347-9939ca861b5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-questionnaire-form-icon&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-questionnaire-form-icon&quot;]</value>
   </webElementProperties>
</WebElementEntity>
