<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Target_Res_Object</name>
   <tag></tag>
   <elementGuidId>98e64a28-08c4-449f-a6f6-e57e46ce528c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='scs-formdesigner-select-resource-grid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='scs-formdesigner-select-resource-grid']</value>
   </webElementProperties>
</WebElementEntity>
