<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClickResource</name>
   <tag></tag>
   <elementGuidId>1bbd24e1-487f-48c4-9e5b-b50e99ba2045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-ts-step2&quot;]/div[3]/div[2]/single-select-dropdown-list/div/span/span/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-ts-step2&quot;]/div[3]/div[2]/single-select-dropdown-list/div/span/span/span[1]</value>
   </webElementProperties>
</WebElementEntity>
