<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_taskButton</name>
   <tag></tag>
   <elementGuidId>e4ca9956-6f45-4e20-b742-82f16f51cd1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;content&quot;]/div/div/div/div/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]/div/div/div/div/div[3]/div/span</value>
   </webElementProperties>
</WebElementEntity>
