<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectResource</name>
   <tag></tag>
   <elementGuidId>24edf27f-986c-4949-9040-3b9e072e4d80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-add-schedule-Resource_listbox&quot;]/li/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-add-schedule-Resource_listbox&quot;]/li/div/div[1]</value>
   </webElementProperties>
</WebElementEntity>
