<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>advance_Button</name>
   <tag></tag>
   <elementGuidId>9c1abfb9-d692-4b77-bd0a-bb2f8981f729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-designform-form-content-prop-conteiner&quot;]/div/div/div[contains(text(),&quot;Advanced&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-designform-form-content-prop-conteiner&quot;]/div/div/div[contains(text(),&quot;Advanced&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
