<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>attrubute_Field_input</name>
   <tag></tag>
   <elementGuidId>2d3aa5b6-852e-4df3-86d0-988cc5e3611f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-rule-builder-container&quot;]/div/div/div/div/div/span/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-rule-builder-container&quot;]/div/div/div/div/div/span/span/input</value>
   </webElementProperties>
</WebElementEntity>
