<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ifStatementArea</name>
   <tag></tag>
   <elementGuidId>cd6f6f5a-6346-451b-992a-4e4a73e1e2c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-rule-builder-container&quot;]/div/div/div[1]/div[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;scs-rule-builder-container&quot;]/div[2]/div/div[1]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-rule-builder-container&quot;]/div/div/div[1]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
