<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option1_Value</name>
   <tag></tag>
   <elementGuidId>4cc86492-ba63-4013-b607-36d0ff81ad3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-rule-builder-container&quot;]/div/div/div/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-rule-builder-container&quot;]/div/div/div/div/div/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
