<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>WorkGroupObject</description>
   <name>WorkGroupObject</name>
   <tag></tag>
   <elementGuidId>66486612-1e47-4db6-a9e9-630a395374a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-popup&quot;]/add-edit-user/form/div/div[9]/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-popup&quot;]/add-edit-user/form/div/div[9]/div[2]/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
