<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectDocument</name>
   <tag></tag>
   <elementGuidId>e14b6d47-8885-46fa-ae5e-0f16cd3490cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr[1]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[1]/td[3]</value>
   </webElementProperties>
</WebElementEntity>
