<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ToCheckElementIsTicked</description>
   <name>ToCheckElementIsTicked</name>
   <tag></tag>
   <elementGuidId>f8c9b4c7-11fc-4cfb-84e2-fbc3db92875a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-manage-roles-user-grid-container&quot;]/div[2]/table/tbody/tr/td[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-manage-roles-user-grid-container&quot;]/div[2]/table/tbody/tr/td[1]/input</value>
   </webElementProperties>
</WebElementEntity>
