<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logoutUser</name>
   <tag></tag>
   <elementGuidId>2173351a-f41e-4f3d-a8a7-1fd2c40aed0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/ul/li/span[contains(text(),&quot;Log&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/ul/li/span[contains(text(),&quot;Log&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
