<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>moveToUser</name>
   <tag></tag>
   <elementGuidId>7f10d1e0-816b-4eb1-83da-9e7799cadaac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-admin-page-panel-grid&quot;]//tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-admin-page-panel-grid&quot;]//tr/td[2]</value>
   </webElementProperties>
</WebElementEntity>
