<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>openUserOptions</name>
   <tag></tag>
   <elementGuidId>6eb20a76-829e-4fd1-9e7f-f49fadd9b1e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-admin-page-panel-grid&quot;]//tr/td[last()]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-admin-page-panel-grid&quot;]//tr/td[last()]/i</value>
   </webElementProperties>
</WebElementEntity>
