<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>roleOpen</name>
   <tag></tag>
   <elementGuidId>30d77f54-6f65-4612-9ee0-bf23f9fdc31d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-popup&quot;]//div[div[contains(text(),&quot;Role(s)&quot;)]]/div/div/div[last()]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-popup&quot;]//div[div[contains(text(),&quot;Role(s)&quot;)]]/div/div/div[last()]</value>
   </webElementProperties>
</WebElementEntity>
