<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectTimeZone</name>
   <tag></tag>
   <elementGuidId>0d0bcab4-d232-441b-b86e-ae2285a0fd36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-admin-tools-manage-resources-user-timezone_listbox&quot;]/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-admin-tools-manage-resources-user-timezone_listbox&quot;]/li[2]</value>
   </webElementProperties>
</WebElementEntity>
