<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectLocation</name>
   <tag></tag>
   <elementGuidId>61ab8e2b-62c9-4214-8670-8f9292dd4a4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;locMultiSelect_listbox&quot;]/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;locMultiSelect_listbox&quot;]/li[2]</value>
   </webElementProperties>
</WebElementEntity>
