<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>timeZoneOpen</name>
   <tag></tag>
   <elementGuidId>7b006546-b1cf-4eb5-bf35-670b8903ff73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-popup&quot;]//div[div[contains(text(),&quot;Timezone&quot;)]]//span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-popup&quot;]//div[div[contains(text(),&quot;Timezone&quot;)]]//span[1]</value>
   </webElementProperties>
</WebElementEntity>
