<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addSupplierPlus</name>
   <tag></tag>
   <elementGuidId>4f7c5f95-15c9-4997-8a3e-68c9ab948a14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-partner-portal&quot;]//list-view[1]//div[@class=&quot;scs-bottom-button-container&quot;]/div[1]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-partner-portal&quot;]//list-view[1]//div[@class=&quot;scs-bottom-button-container&quot;]/div[1]/i</value>
   </webElementProperties>
</WebElementEntity>
