<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bold</name>
   <tag></tag>
   <elementGuidId>fa8aa900-ded4-4c77-9eb7-adc515b55e56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-editor-acknowledgement-container&quot;]/table/tbody/tr[1]/td/ul/li[1]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-editor-acknowledgement-container&quot;]/table/tbody/tr[1]/td/ul/li[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
