<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkUserinWG</name>
   <tag></tag>
   <elementGuidId>f78b6cc0-be9a-4b14-8567-c81f7706a9a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-mwg-grid-container-id&quot;]//tr/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-mwg-grid-container-id&quot;]//tr/td[1]</value>
   </webElementProperties>
</WebElementEntity>
