<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickOnSuppReject</name>
   <tag></tag>
   <elementGuidId>76670033-dcdc-4968-bcdc-cfb71a8c39ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='supplier-inbox-grid']//tr[1]/td[3]/strong[contains(text(),'Rejected')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='supplier-inbox-grid']//tr[1]/td[3]/strong[contains(text(),'Rejected')]</value>
   </webElementProperties>
</WebElementEntity>
