<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>expirtionDate_ApproveTask</name>
   <tag></tag>
   <elementGuidId>00076539-d9b0-44ba-bb51-d9c79dcee9fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-doc-expiry-date-picker&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-doc-expiry-date-picker&quot;]</value>
   </webElementProperties>
</WebElementEntity>
