<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemsTabInReq</name>
   <tag></tag>
   <elementGuidId>90c39252-f9ae-49d5-b819-b9a5b49a830a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SupplierItemsGrid&quot;]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SupplierItemsGrid&quot;]/span[2]</value>
   </webElementProperties>
</WebElementEntity>
