<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nextButtonReqForm</name>
   <tag></tag>
   <elementGuidId>121cae25-925e-49d7-8bc7-0220bcd14109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-steps-buttons-holder&quot;]/step-wizard-buttons//span[contains(text(),&quot;NEXT&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-steps-buttons-holder&quot;]/step-wizard-buttons//span[contains(text(),&quot;NEXT&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
