<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>openSupplierOption</name>
   <tag></tag>
   <elementGuidId>13468d9f-f448-4005-a6fe-a722b127ced0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-add-new-supplier-user-template-holder&quot;]/form/div[div[contains(text(),&quot;Supplier(s)&quot;)]]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-add-new-supplier-user-template-holder&quot;]/form/div[div[contains(text(),&quot;Supplier(s)&quot;)]]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
