<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>optionToSelectNewRequirement</name>
   <tag></tag>
   <elementGuidId>4439541a-7dcc-40ef-a5f2-bfcc2cbee48f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-product-dropdown&quot;]/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-product-dropdown&quot;]/li/span</value>
   </webElementProperties>
</WebElementEntity>
