<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saveButtonTask</name>
   <tag></tag>
   <elementGuidId>1ef7e5cd-8aba-4e5e-ba9b-c8e42c8abac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-steps-buttons-holder&quot;]/step-wizard-buttons//span[contains(text(),&quot;SAVE&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-steps-buttons-holder&quot;]/step-wizard-buttons//span[contains(text(),&quot;SAVE&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
