<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saveInWG</name>
   <tag></tag>
   <elementGuidId>2538acd9-ef9f-4e53-a652-a74b3c4d8a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-manage-work-groups&quot;]//div[contains(text(),&quot;SAVE&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-manage-work-groups&quot;]//div[contains(text(),&quot;SAVE&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
