<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectSupplierTab</name>
   <tag></tag>
   <elementGuidId>8a09f8f4-502a-47bf-8a37-ca821ee85621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SupplierGrid&quot;]/span[last()]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SupplierGrid&quot;]/span[last()]</value>
   </webElementProperties>
</WebElementEntity>
