<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectNewSupplier</name>
   <tag></tag>
   <elementGuidId>455a5e99-2e3f-4fc2-a645-a4887035aad1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button</value>
   </webElementProperties>
</WebElementEntity>
