<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectReqFormInSupp</name>
   <tag></tag>
   <elementGuidId>36c9123d-a997-4197-8296-314966366e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;supplier-inbox-grid&quot;]//td[3]/span/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;supplier-inbox-grid&quot;]//td[3]/span/strong</value>
   </webElementProperties>
</WebElementEntity>
