<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectForm</name>
   <tag></tag>
   <elementGuidId>b8b8fe16-6008-4417-95f7-8e7e2307b7e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-pp-acknowledgement-step-1-grid-container&quot;]/div[2]/table/tbody/tr[7]/td[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-pp-acknowledgement-step-1-grid-container&quot;]/div[2]/table/tbody/tr[7]/td[1]/label</value>
   </webElementProperties>
</WebElementEntity>
