<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>setSupplierInRequirement</name>
   <tag></tag>
   <elementGuidId>d15dc577-961b-4db8-bbb1-fd71f457911a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-pp-list-view-data&quot;]/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-pp-list-view-data&quot;]/div/div/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
