<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>supplierTabInRequirement</name>
   <tag></tag>
   <elementGuidId>d20a179f-d0dc-41bd-b496-9a321f95cedf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SupplierItemsGrid&quot;]/span[last()]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SupplierItemsGrid&quot;]/span[last()]</value>
   </webElementProperties>
</WebElementEntity>
