<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>testDoc</name>
   <tag></tag>
   <elementGuidId>1ccbf0e0-f9c6-4b9c-98de-fecefda052b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-pp-acknowledgement-step-1-grid-container&quot;]//tr[1]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-pp-acknowledgement-step-1-grid-container&quot;]//tr[1]/td[2]</value>
   </webElementProperties>
</WebElementEntity>
