<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>testACK</name>
   <tag></tag>
   <elementGuidId>f7706bf2-89d9-441c-a6e3-4d462628f8f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-pp-acknowledgement-step-1-grid-container&quot;]//tr[1]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-pp-acknowledgement-step-1-grid-container&quot;]//tr[1]/td[3]</value>
   </webElementProperties>
</WebElementEntity>
