<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Resource</name>
   <tag></tag>
   <elementGuidId>09db7ecd-125f-4bbe-a041-272af89d33ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-add-schedule-Resource_listbox&quot;]/li[1]/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-add-schedule-Resource_listbox&quot;]/li[1]/div/div[1]</value>
   </webElementProperties>
</WebElementEntity>
