<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button2Save</name>
   <tag></tag>
   <elementGuidId>351fb4fc-d1ed-43c4-bb63-b34cb71e0d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[2]</value>
   </webElementProperties>
</WebElementEntity>
