<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>customers</name>
   <tag></tag>
   <elementGuidId>1ae3a733-2092-4a9c-a471-bd1e85a28b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-manage-resource-list-view-data&quot;]/div/div/div/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-manage-resource-list-view-data&quot;]/div/div/div/div[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
