<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>equipment</name>
   <tag></tag>
   <elementGuidId>6ad9db3a-b122-4fe4-a168-7ea554a484bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-manage-resource-list-view-data&quot;]/div/div/div/div[2]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-manage-resource-list-view-data&quot;]/div/div/div/div[2]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
