<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linksTab</name>
   <tag></tag>
   <elementGuidId>0c71019d-3fbb-41a9-a06b-f37d97e3aab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tabstrip&quot;]/ul/li[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tabstrip&quot;]/ul/li[2]/span[2]</value>
   </webElementProperties>
</WebElementEntity>
