<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mainMenu_resources</name>
   <tag></tag>
   <elementGuidId>01e34a56-9c0e-44ef-8124-d15ee4a46d75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-main-navigation&quot;]//div[contains(text(),&quot;Resources&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-main-navigation&quot;]//div[contains(text(),&quot;Resources&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
