<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>setPhoneNumber</name>
   <tag></tag>
   <elementGuidId>61efb647-9c10-4e1e-9d3a-427322d4b618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scsResourceDetails&quot;]//span/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scsResourceDetails&quot;]//span/input[1]</value>
   </webElementProperties>
</WebElementEntity>
