<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>supplierTab</name>
   <tag></tag>
   <elementGuidId>1e0d802f-0238-4317-a403-130fc85d9971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tabstrip&quot;]//span[contains(text(),&quot;Suppliers&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tabstrip&quot;]//span[contains(text(),&quot;Suppliers&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
