<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SuppliersDesign</name>
   <tag></tag>
   <elementGuidId>a80a7421-ec01-416f-b0ff-edaabee2e3b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-manage-resource-list-view-data&quot;]/div/div/div/div[5]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-manage-resource-list-view-data&quot;]/div/div/div/div[5]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
