<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chooseFirstForm</name>
   <tag></tag>
   <elementGuidId>f5a8bd62-1733-4614-931a-81b119f2a9fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-dpt-filters-grid&quot;]//tr[1]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-dpt-filters-grid&quot;]//tr[1]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
