<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>import-export</name>
   <tag></tag>
   <elementGuidId>58378bce-d5f7-439f-92e9-d82ec6eff4f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-main-navigation&quot;]//div[contains(text(),&quot;Data&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-main-navigation&quot;]//div[contains(text(),&quot;Data&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
