<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>import</name>
   <tag></tag>
   <elementGuidId>bacb1a47-a9f3-43ed-ae9c-527adb3108d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;dataprovisioning-tabstrip&quot;]//span[contains(text(),&quot;Import&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;dataprovisioning-tabstrip&quot;]//span[contains(text(),&quot;Import&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
