<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectFormImport</name>
   <tag></tag>
   <elementGuidId>20947d6e-2ade-4045-8f52-6aabaf775687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-data-provisioning-import-grid-container&quot;]//tr[1]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-data-provisioning-import-grid-container&quot;]//tr[1]/td[4]</value>
   </webElementProperties>
</WebElementEntity>
