<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickToOpenFormActions</name>
   <tag></tag>
   <elementGuidId>3a34f69d-caf5-445a-b361-872739d5b89c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-forms-grid&quot;]/div[2]/table/tbody/tr/td[6]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-forms-grid&quot;]/div[2]/table/tbody/tr/td[6]/i</value>
   </webElementProperties>
</WebElementEntity>
