<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Over</name>
   <tag></tag>
   <elementGuidId>af057bc9-3434-43b0-bcca-489f9b18bc46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-forms-grid&quot;]/div[2]/table/tbody/tr/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-forms-grid&quot;]/div[2]/table/tbody/tr/td[1]</value>
   </webElementProperties>
</WebElementEntity>
