<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>task_FilterButton</name>
   <tag></tag>
   <elementGuidId>ffb8e84f-1326-4f6d-b205-0b93cac2aaef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[last()]/div/ul/li/div/ul/li/div/form/div/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[last()]/div/ul/li/div/ul/li/div/form/div/div/button[1]</value>
   </webElementProperties>
</WebElementEntity>
