<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>task_FilterOption</name>
   <tag></tag>
   <elementGuidId>1fd59111-cb57-47d1-ab6f-5cc21f29aee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[last()]/div/ul/li[last()]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[last()]/div/ul/li[last()]/span</value>
   </webElementProperties>
</WebElementEntity>
