<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>options</name>
   <tag></tag>
   <elementGuidId>99d8c96e-9e70-4bf2-a67b-dca538ea1f4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;scs-forms-grid&quot;]/div/div/table/thead/tr/th[1]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;scs-forms-grid&quot;]/div/div/table/thead/tr/th[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
